### ISSUE TITLE
40xbypass功能点击stop后还会继续运行

### ISSUE THREAD

**Issue by MTY123-YF** [TideSec/TscanPlus#100]
![tide1](https://github.com/user-attachments/assets/6928e4d5-5498-4a03-80f7-bc01e347dc8b)

![tide2](https://github.com/user-attachments/assets/004b8a1d-ece4-472d-9f15-c020ca0e382e)
这是bug还是我操作有误，或者说就是这样的？

**Comment by TideSec** [comment]
这个功能是这次新加的功能，我回头复现排查下，感谢师傅反馈。

**Comment by MTY123-YF** [comment]
好的

**Comment by TideSec** [comment]
感谢师傅，下个版本已经修复，致谢+1

**Comment by MTY123-YF** [comment]
哈哈哈，略尽绵薄之力
