### ISSUE TITLE
项目管理文字颜色问题

### ISSUE THREAD

**Issue by Jan-Thirteen** [TideSec/TscanPlus#102]
项目管理页面选中一条项目后项目任务的字体颜色难以辨认
![image](https://github.com/user-attachments/assets/d975999c-1797-4c11-836c-d50afd31176e)

**Comment by TideSec** [comment]
感谢师傅反馈，回头调整下这个配色，开发主要是在浅色模式下，所以暗黑主题的有些显示不太友好。
