### ISSUE TITLE
建议添加自动调整线程功能或者优化内存管理

### ISSUE THREAD

**Issue by 1337Player** [TideSec/TscanPlus#103]
最近在红队项目中遇到的问题：红队项目目标资产很多(我这个上万条)需要快速打点，发现tscan的端口扫描在100，200线程，500线程，1000线程的情况下均存在不定时内存占用瞬间飙升128G导致软件崩溃现象(一般不会，但是出现大概率就是崩溃)，该现象随机发生，前几个版本和2.2tscan版本都存在此现象，晚上睡觉挂机收集资产，跑一会自己就崩溃了，醒来发现软件崩了之前跑的结果还全没了，使用体验很差，靶标资产根本收集不全，希望作者改进一下

**Comment by TideSec** [comment]
目前也发现这个问题了，主要是go+wails框架的问题，导致系统资源占用很高，有时候直接被系统卡退了，后面会完善这个自动化调整功能。
