### ISSUE TITLE
运行出错

### ISSUE THREAD

**Issue by jobsgxx** [TideSec/TscanPlus#105]
# ./TscanPlus_Linux_Amd64 
DbFile: /data/TscanPlus/TscanPlus-v2.2/config/config.db
UserCfgDir: /data/TscanPlus/TscanPlus-v2.2/config
Unable to init server: Could not connect: Connection refused
panic: failed to init GTK

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
        github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:145 +0x139
sync.(*Once).doSlow(0x465449?, 0xc000c4c0f5?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x22b7ce0, 0xc005c3ef60}, 0xc00384b8c0, 0xc003077c80, 0xc0013bcee0, {0x22adc20, 0xc004234700})
        github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:136 +0x77
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...)
        github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/desktop_linux.go:16
github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc00384b8c0)
        github.com/wailsapp/wails/v2@v2.8.0/internal/app/app_production.go:86 +0x5af
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc005cd9d40)
        github.com/wailsapp/wails/v2@v2.8.0/pkg/application/application.go:58 +0x25
github.com/wailsapp/wails/v2.Run(0xc00384b8c0?)
        github.com/wailsapp/wails/v2@v2.8.0/wails.go:14 +0x9a
main.main()
        TscanGui/main.go:36 +0x28f

**Comment by TideSec** [comment]
你应该是在命令行下使用的，无影是GUI程序，必须运行在linux的图形界面下才行。
