### ISSUE TITLE
空间测绘模块配置了fofa API后也查不出来数据

### ISSUE THREAD

**Issue by Kiand1** [TideSec/TscanPlus#106]
空间测绘模块配置了fofa API后也查不出来数据
![Uploading Snipaste_2024-07-31_15-17-51.png…]()

**Comment by Kiand1** [comment]
<img width="1172" alt="Snipaste_2024-07-31_15-17-51" src="https://github.com/user-attachments/assets/0a2a6a10-2b02-463f-97ec-324efe435ba8">

**Comment by TideSec** [comment]
配置key之后可以点下验证看看是否能用，该功能一直都是正常的，如果key没问题，可以查看下网络或是否配置代理等。
