### ISSUE TITLE
用友nc 识别不出来？ehole能识别出来

### ISSUE THREAD

**Issue by wlaq-su** [TideSec/TscanPlus#11]

**Comment by wlaq-su** [comment]
![image](https://github.com/TideSec/TscanPlus/assets/65948791/3a1eb559-f0ad-4522-b359-8ca738ae8965)
![image](https://github.com/TideSec/TscanPlus/assets/65948791/49a76cb5-54ff-4b85-a79b-39a239af7ef0)

**Comment by TideSec** [comment]
感谢反馈，需求已经记录，预计1.3版本会修复这个问题。
