### ISSUE TITLE
进度bug

### ISSUE THREAD

**Issue by sumo166** [TideSec/TscanPlus#110]
![image](https://github.com/user-attachments/assets/fac87708-7911-4a3d-bb0b-2e503101a021)
![image](https://github.com/user-attachments/assets/6f1688e1-f03f-4ff8-ad1e-586dcffc65b1)

所有的操作已经完成，不显示完成，能不能在项目管理加个进度条？？？？？？？？？？？？？？？？？？？？？？？？？？？

**Comment by sumo166** [comment]
![image](https://github.com/user-attachments/assets/667c7a29-4c04-4662-811b-555e3a0e9835)

**Comment by TideSec** [comment]
2.3版加了日志功能，可以查看后台日志。另外项目任务的颜色是显示进度的。
