### ISSUE TITLE
win 11切换窗口即闪退

### ISSUE THREAD

**Issue by x1an9ch** [TideSec/TscanPlus#111]
打开软件后点击其他窗口，再点击该软件窗口后，软件直接闪退，无法使用。

**Comment by TideSec** [comment]
是每次都闪退么？

**Comment by x1an9ch** [comment]
今天又尝试了下，莫名又好了，之前点开后点击桌面再点击工具窗口就会闪退，不清楚是什么原因

**Comment by TideSec** [comment]
感谢~ win11有时候会因为主题或组件原因导致闪退，可以尝试卸载webview并重装。
