### ISSUE TITLE
IP存活量达到一定量程序自动退出

### ISSUE THREAD

**Issue by leemeng1999** [TideSec/TscanPlus#113]
探测IP范围如10.100.1.0/16，使用全端口扫描，存活IP4000+个时，存活进度100%后，程序自动退出。

**Comment by TideSec** [comment]
https://github.com/TideSec/TscanPlus/releases/tag/v2.3   更新了一个2.3.1版，应该能解决你这个问题。

**Comment by leemeng1999** [comment]
师傅，提交bug有效，页修复了，是否可以给一个key，软件上写了提交有效bug并修复可以获取一个！
