### ISSUE TITLE
多ip弱密码检测的时候闪退

### ISSUE THREAD

**Issue by yehao1991** [TideSec/TscanPlus#114]
多ip弱密码检测的时候闪退

**Comment by TideSec** [comment]
用的哪个版本的？有没有具体使用场景？选的什么服务，有多少ip资产？

**Comment by yehao1991** [comment]
1、版本是v2.3；2、场景是密码破解：192.168.0.0/16；3、服务全选；4、大概600+IP；6、检测到30000多的时候闪退；

**Comment by yehao1991** [comment]
> 1、版本是v2.3；2、场景是密码破解：192.168.0.0/16；3、服务全选；4、大概600+IP；6、检测到30000多的时候闪退；

![image](https://github.com/user-attachments/assets/4bc84964-a25e-4981-a475-482009112e1a)

**Comment by yehao1991** [comment]
队列检测大概到35000+后闪退

**Comment by TideSec** [comment]
跑了一个B段，没复现出来，不知道是因为bug闪退，还是因为内存或CPU满了后被操作系统卡退。方便加一个微信么secplus~

**Comment by TideSec** [comment]
已查明问题，2.4版本会修复，感谢。
