### ISSUE TITLE
自动关闭

### ISSUE THREAD

**Issue by j1dag** [TideSec/TscanPlus#117]
为什么扫描完成会自动关闭

**Comment by TideSec** [comment]
做的什么扫描？具体场景请描述一下

**Comment by kkkyan** [comment]
我是扫一个内网ip，全端口，不知道是否扫描完，版本2.3.1，日志最后是，然后就闪退了：
`[2024-08-23 11:16:28] [INF] 扫描 172.17.*.*:62225 结束,耗时: 18.0667158s`

**Comment by TideSec** [comment]
应该是没扫描完，是每次都这样么？

> 我是扫一个内网ip，全端口，不知道是否扫描完，版本2.3.1，日志最后是，然后就闪退了： `[2024-08-23 11:16:28] [INF] 扫描 172.17.*.*:62225 结束,耗时: 18.0667158s`

**Comment by j1dag** [comment]
@TideSec 不是每次都这样是大多数情况，还是有不关闭的时候

**Comment by kkkyan** [comment]
> 应该是没扫描完，是每次都这样么？
> 
> > 我是扫一个内网ip，全端口，不知道是否扫描完，版本2.3.1，日志最后是，然后就闪退了： `[2024-08-23 11:16:28] [INF] 扫描 172.17.*.*:62225 结束,耗时: 18.0667158s`

我好像是每次都这样，我这个IP就没扫完过

**Comment by TideSec** [comment]
感觉各位，已经复现该问题，是2.3添加新功能时引入的bug，2.4已修复，近期会发布~
