### ISSUE TITLE
FTP密码破解怎么指定用户名？

### ISSUE THREAD

**Issue by b2522** [TideSec/TscanPlus#118]
设置了使用内置字典，里面有几个用户名，可也只跑匿名的，怎么指定用户名呢？

用的最新2.3版本。

![image](https://github.com/user-attachments/assets/31ba3f7b-51c8-4783-9df4-bed20d5e0040)

**Comment by TideSec** [comment]
感谢师傅反馈，2.4版本已修复该问题，近期会发布~

**Comment by b2522** [comment]
> 感谢师傅反馈，2.4版本已修复该问题，近期会发布~

感谢师傅的工具，看说明提交bug是可以获取一个Key，请问还能获取吗？
还有个问题，工具收集到的敏感信息是什么，在哪里查看，实在是没找到。
![image](https://github.com/user-attachments/assets/fa58ec78-0833-4864-8602-f489af16e687)
