### ISSUE TITLE
hunter api问题

### ISSUE THREAD

**Issue by haochen1204** [TideSec/TscanPlus#121]
hunter搜索有600多条结果
配置api后工具搜索，一会100条，一会200条 一会400条，就是搜不全

**Comment by TideSec** [comment]
<img width="968" alt="image" src="https://github.com/user-attachments/assets/dba1cbca-3141-4ebc-bead-c752a1509dff">

Hunter默认查询页码数为5页(每页100条)，可在config.yaml文件中通过参数HunterPages自行设置。
