### ISSUE TITLE
windows版本2.3.1端口扫描队列异常，线程设置无效

### ISSUE THREAD

**Issue by zhuanyedecainiao** [TideSec/TscanPlus#122]
队列瞬间完成，设置线程10，实际仍快速结束。应该是配置未生效，建议进行修补bug

**Comment by TideSec** [comment]
快速结束应该是没探测到目标存活，如果确定目标存活的话，可以把“ping扫描”选项关闭再试一下。
<img width="873" alt="image" src="https://github.com/user-attachments/assets/b0ff8f9e-380f-4abf-8e5d-c09464cf3a41">

**Comment by TideSec** [comment]
2.4版已经发布，师傅可以下载最新版本尝试。
