### ISSUE TITLE
功能疑问-在端口扫描页面选中端口进行密码破解后，怎么停止它？

### ISSUE THREAD

**Issue by lzj242** [TideSec/TscanPlus#129]
![image](https://github.com/user-attachments/assets/2ba89eca-2e99-4649-bb52-bc1e8aa0f562)
![image](https://github.com/user-attachments/assets/397507ae-f7d4-4680-a8ed-5a0b82e3aad6)

**Comment by TideSec** [comment]
在密码破解页面点下Stop可以停止破解，但因为是多线程，可能Stop后会有几个线程结束慢一些。
如果Stop按钮变成了"继续"，那么可以点下“刷新”按钮就会变成Stop。
