### ISSUE TITLE
redis密码显示错误。

### ISSUE THREAD

**Issue by shanxigetanxiaochou** [TideSec/TscanPlus#133]
v2.4版 【2024.09.01】版本redis口令爆破问题。
显示密码为空，实际有密码。通过链接，发现确实密码为123456
<img width="798" alt="图片" src="https://github.com/user-attachments/assets/b148e4b8-11e7-425e-8d57-d051c1a745e9">

**Comment by TideSec** [comment]
感谢，之前已经有师傅反馈，v2.4.1已经修复。
