### ISSUE TITLE
端口扫描bug

### ISSUE THREAD

**Issue by zhizi1234** [TideSec/TscanPlus#136]
![image](https://github.com/user-attachments/assets/8c0abd41-8fe4-4358-8f6a-e78c277fdafa)
![image](https://github.com/user-attachments/assets/c062e2b5-3cda-4df5-9d5c-353d0d58a844)
IP扫描不完整 速度缓慢 当线程过大时 会出现进度条异常

**Comment by TideSec** [comment]
你虽然选的是全端口，但端口号里面不是1-65535，是自定义的端口。
