### ISSUE TITLE
Mac ARM版本 M系列芯片无法打开

### ISSUE THREAD

**Issue by li-baige** [TideSec/TscanPlus#14]
打开就闪退，作者麻烦看看

**Comment by TideSec** [comment]
看下FAQ部分，闪退一般是mac的签名问题。

Mac上可能遇到不少执行问题，如「xxx已损坏，无法打开，您应该将它移到废纸篓」、「打不开xxx，因为 Apple 无法检查其是否包含恶意软件」、「打不开 xxx，因为它来自身份不明的开发者」，可参考下面两篇文章，基本能解决95%的问题。

https://cloud.tencent.com/developer/article/2216717?areaId=106001 【苹果电脑安装软件后，提示mac文件已损坏,无法打开怎么办？】 https://sysin.org/blog/macos-if-crashes-when-opening/ 【macOS 提示：“应用程序” 已损坏，无法打开的解决方法总结】

目前Mac遇到的比较多的就是闪退问题，执行下面的命令即可解决：

sudo xattr -r -d com.apple.quarantine TscanPlus_darwin_amd64_v1.0.app

如果还是不行，再执行这个：

sudo codesign --sign - --force --deep TscanPlus_darwin_amd64_v1.0.app

**Comment by li-baige** [comment]
非常感谢作者～，问题已经解决。
