### ISSUE TITLE
Fofa API小 BUG

### ISSUE THREAD

**Issue by examenes3** [TideSec/TscanPlus#140]
空间测绘的 fofa API如果只使用 api key 则无法调用
![image](https://github.com/user-attachments/assets/35f280ed-8b5e-44b7-af10-cff02cc1b4f9)
![image](https://github.com/user-attachments/assets/61c6caf3-3f13-43b0-a7ef-4da2fbaa5723)
需要添加一个任意邮箱后才可以调用
![image](https://github.com/user-attachments/assets/f2505ee4-fb1e-4e97-b90e-82041b378a94)
![image](https://github.com/user-attachments/assets/e21a2016-4785-4900-ba3f-af09f0f86bdd)

**Comment by TideSec** [comment]
fofa之前的api需要校验邮箱，所以就保留了之前的格式要求，现在可以随便输一个邮箱就可以。
