### ISSUE TITLE
ssh爆破时关于密钥交换存在bug

### ISSUE THREAD

**Issue by dongluliang** [TideSec/TscanPlus#141]
在对内网进行sss暴力破解时时发现大量的数据包在密钥交换环节失效，导致爆破失败。
日志：

[-] ssh 192.168.1.1:22 admin admin@12345 ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 diffie-hellman-group14-sha1 ext-info-c kex-strict-c-v00@openssh.com], server offered: [diffie-hellman-group-exchange-sha1 diffie-hellman-group1-sha1]

[-] ssh 192.168.1.2:22 root admin123 ssh: handshake failed: ssh: no common algorithm for key exchange; client offered: [curve25519-sha256 curve25519-sha256@libssh.org ecdh-sha2-nistp256 ecdh-sha2-nistp384 ecdh-sha2-nistp521 diffie-hellman-group14-sha256 diffie-hellman-group14-sha1 ext-info-c kex-strict-c-v00@openssh.com], server offered: [diffie-hellman-group-exchange-sha1 diffie-hellman-group1-sha1]

......

**Comment by TideSec** [comment]
这个可能是个例情况，我试过不少的ssh破解，大部分都算正常。
