### ISSUE TITLE
#端口扫描模块，默认文件生成模块，测绘模块

### ISSUE THREAD

**Issue by Serein-vr** [TideSec/TscanPlus#142]
端口扫描，在mac上扫描精度和准确度大幅下降，之前版本可以扫描出来。
mac修改默认输出txt的位置，一直无法成功修改，而且每个模块的配置还要进行重新修改。重启之后又回归原样。
测绘模块，建议提供fofa的api自定义，然后添加hunter多个key的输出。优化查询
建议增加企业查询相关功能，站长工具，天眼查，企查查。进行单位名的批量查询，然后导出相关备案资产。进行联动其他相关模块
建议提供一个linux的一个命令行参数，或者提供一个web页面。进而可以用vps进行批量扫描

**Comment by TideSec** [comment]
v2.5.2之后端口扫描功能增加了线程和超时设置，这两个参数可以搭配调一下，根据自己的网络情况设置一个合理的值。
mac修改默认输出txt的位置应该没问题的，可以自行设置。
fofa的api自定义一直可以自定义，可以看api设置的备注帮助信息。
企业查询相关的内容后面可能会考虑，目前工具定位暂时只做主动资产探测和识别。
