### ISSUE TITLE
编码转换bug

### ISSUE THREAD

**Issue by omegazero01** [TideSec/TscanPlus#144]
编码转换有个bug，创建两个tab，tab1选择sm2加解密，输入公钥、私钥，如下图
![image](https://github.com/user-attachments/assets/38ced977-e918-4607-a1a7-8093ca948d92)
选择tab2，再切回tab1，tab1内的公钥、私钥就会自动清空，如下图
![image](https://github.com/user-attachments/assets/c8ce6ec9-d1c5-460d-8d90-30232fd9425e)

**Comment by omegazero01** [comment]
还有个问题就是，加解密都需要同时输入公钥私钥，但加密只需要公钥即可，解密只需要私钥即可

**Comment by TideSec** [comment]
切换tab后数据丢失的问题目前暂时无法解决，第二个加解密都需要同时输入公钥私钥的bug已经解决，下个版本修复，感谢师傅。
