### ISSUE TITLE
运行闪退问题

### ISSUE THREAD

**Issue by Another-YY** [TideSec/TscanPlus#145]
第二次遇见这问题了，打开后点击边框，切屏再点回来，都会自动退出，之前也碰见过，那次不知道怎么自己好了
https://github.com/user-attachments/assets/32957371-7bb3-4b58-a3c4-3b4b416bfb4f

**Comment by TideSec** [comment]
师傅是win11系统么，有没有使用一些主题美化之类的软件，如果有的话，关掉那些主题美化或桌面管理的软件试下。

**Comment by Another-YY** [comment]
用的win10，不过没事儿了，现在自己又好了，挺奇怪

**Comment by TideSec** [comment]
可以换最新的版本试一下~
