### ISSUE TITLE
Mac运行闪退

### ISSUE THREAD

**Issue by zjz677** [TideSec/TscanPlus#146]
更新了最新的软件 但是还是进不去 点击软件 跳了几下就没了 命令运行了也还是不可以

**Comment by TideSec** [comment]
> 更新了最新的软件 但是还是进不去 点击软件 跳了几下就没了 命令运行了也还是不可以

命令行里面运行后什么提示，能截个图看看么，这样执行

<img width="786" alt="image" src="https://github.com/user-attachments/assets/d436c379-a05d-4b48-8a7e-6a9b24c1635f">

**Comment by zjz677** [comment]
(base) mac@macdeMacBook-Air ~ % cd /Applications/TscanPlus.app 
(base) mac@macdeMacBook-Air TscanPlus.app % sudo xattr -r -d com.apple.quarantine /Applications/TscanPlus.app 
Password:
(base) mac@macdeMacBook-Air TscanPlus.app % sudo codesign --sign - --force --deep /Applications/TscanPlus.app 
/Applications/TscanPlus.app: replacing existing signature
(base) mac@macdeMacBook-Air TscanPlus.app %

**Comment by TideSec** [comment]
> (base) mac@macdeMacBook-Air ~ % cd /Applications/TscanPlus.app (base) mac@macdeMacBook-Air TscanPlus.app % sudo xattr -r -d com.apple.quarantine /Applications/TscanPlus.app Password: (base) mac@macdeMacBook-Air TscanPlus.app % sudo codesign --sign - --force --deep /Applications/TscanPlus.app /Applications/TscanPlus.app: replacing existing signature (base) mac@macdeMacBook-Air TscanPlus.app %

正解，感谢~！
