### ISSUE TITLE
项目管理中的数据统计不准确。

### ISSUE THREAD

**Issue by xiewentu** [TideSec/TscanPlus#151]
如下图，在扫描的时候有弱口令漏洞，但是在项目管理中的数据统计数据不对，如下图。
![图片](https://github.com/user-attachments/assets/54896daf-a9e8-4286-96e7-7b258dcaaa1c)
![图片](https://github.com/user-attachments/assets/678810cc-efa2-4b9e-a085-c56c90924773)

**Comment by TideSec** [comment]
师傅点一下项目管理旁的刷新就可以，软件每次启动的时候也会重新刷新这个数据。
