### ISSUE TITLE
项目管理里扫描到的SQLserver弱口令,但在密码破解里单独指定IP扫描所有的端口却不被提示

### ISSUE THREAD

**Issue by leezm** [TideSec/TscanPlus#152]
如题，之前项目扫描出来的SQLserver弱口令，我想单独扫一下试试，结果就是密码破解里没有扫出来，但我用项目管理里的弱口令去登录发现问题是存在的

**Comment by TideSec** [comment]
这个bug之前有师傅提过，主要是因为联动功能的时候sqlserver和mssql弄混了，导致密码扫描没发现，最新的v2.5.2已经修复了

**Comment by leezm** [comment]
> 这个bug之前有师傅提过，主要是因为联动功能的时候sqlserver和mssql弄混了，导致密码扫描没发现，最新的v2.5.2已经修复了

好的,感谢!
