### ISSUE TITLE
为什么执行扫描目录功能时会报毒呢

### ISSUE THREAD

**Issue by Neojacka** [TideSec/TscanPlus#153]
![image](https://github.com/user-attachments/assets/82be86c7-907e-4815-98d7-3b1e633504c1)
如图

**Comment by TideSec** [comment]
!ml是Defender基于机器学习的检测结果，估计是认为发起大量集中的get请求的行为比较异常，所以报毒了。
如果师傅担心软件有问题，可以自己抓包分析~  另外，软件也要从github官方下载更放心~
