### ISSUE TITLE
2.5.2版本运行一会就空白报错，且清除数据时不会把轻武器库的数据同步清除。

### ISSUE THREAD

**Issue by VBPush** [TideSec/TscanPlus#154]
2.5.2版本运行一会就空白报错，然后崩溃，且清除数据后，不会即时把轻武器库的数据同步清除，需要重启才能清楚数据。
![image](https://github.com/user-attachments/assets/ad37f58c-9153-4e27-b732-cbc2d50011f7)

**Comment by TideSec** [comment]
清除数据后需要刷新一下页面才行，每个页面都有刷新按钮，或者随便切换一下项目也可以。
空白报错可能是升级了官方框架的原因，2.6.0版本会回滚到之前版本。

**Comment by TideSec** [comment]
你卸载并重新安装下webview能解决这个问题  https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download
