### ISSUE TITLE
目录枚举有点小BUG

### ISSUE THREAD

**Issue by Acczdy** [TideSec/TscanPlus#157]
大佬，我用2.5.2版本目录枚举后到处excel发现Title列和Method列反了
![1728723167473](https://github.com/user-attachments/assets/314eb92f-5677-4447-b286-2751322c3818)

**Comment by TideSec** [comment]
感谢师傅，2.6已修复，致谢名单+1 ~

**Comment by Acczdy** [comment]
大佬，现在提BUG没有KEY了哈
