### ISSUE TITLE
quake的资产测绘

### ISSUE THREAD

**Issue by xjp08** [TideSec/TscanPlus#158]
![image](https://github.com/user-attachments/assets/decc2db1-d872-441b-842a-8f94f79d0c9d)

都是500个，是接口做了限制吗

**Comment by TideSec** [comment]
感谢师傅，这个之前是设置了固定最大值500，在下个版本2.6中的config.yaml中，添加了一个参数EnginePages，这个是设置了获取页码的数，可以进行自定义。致谢名单+1
<img width="699" alt="image" src="https://github.com/user-attachments/assets/3bb7861a-dad1-4a69-9a85-8d7a834568a2">
