### ISSUE TITLE
非常规端口扫描后只有常规端口才会进行爆破

### ISSUE THREAD

**Issue by jisanlong** [TideSec/TscanPlus#16]
端口扫描选项，非常规端口扫描后只有常规端口才会进行爆破，而非常规端口识别出来是mysql或者ssh就不会爆破  是否可以根据指纹识别出来的服务进行爆破

**Comment by TideSec** [comment]
对，联动任务时目前是根据端口号进行判断，主要是担心服务识别不准确的误爆破，目前可以在端口扫描后，右键添加制定爆破任务。你这个需求已经记录，后面也会完善的，感谢反馈。
