### ISSUE TITLE
使用密码破解功能会自动关闭程序

### ISSUE THREAD

**Issue by dark-unshell** [TideSec/TscanPlus#164]
使用密码破解功能，会自动关闭程序，尤其是使用大字典的时候。

建议修改端口扫描导出的功能，默认是导出excel，导出的很多内容不需要

可以修改为导出.txt文件，和导出到指定文件夹。

**Comment by TideSec** [comment]
目前所有的日志和记录都会在TscanPlus-Result.txt文件中留存一份。
导出文件夹可以在高级配置里面自己设置。
大字典容易导致内存不足，因而闪退，尽量字典不要太大。
