### ISSUE TITLE
错误代码：out of memory

### ISSUE THREAD

**Issue by dongluliang** [TideSec/TscanPlus#165]
换了三台电脑，点击密码破解标签页会提示：此页面存在问题
![微信截图_20241021084441](https://github.com/user-attachments/assets/b1f38cad-7c5b-4a6e-9290-08af85a0de02)
错误代码：out of memory

**Comment by TideSec** [comment]
> 换了三台电脑，点击密码破解标签页会提示：此页面存在问题

你这个是不是数据库里数据太多，你可以把config目录下的config.db文件删除或重命名试下，程序会自动生成个空的db文件。
