### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by mysterious-sec** [TideSec/TscanPlus#166]
与上个版本存在同样的问题，windows10系统会出现报错闪退；老版本使用正常
![image](https://github.com/user-attachments/assets/bf1b43bc-7f91-4908-94d2-d05e15ac8fa9)

**Comment by TideSec** [comment]
这是你的webview2问题，你卸载本机webview2后重新安装一下 
https://developer.microsoft.com/en-us/microsoft-edge/webview2/
