### ISSUE TITLE
目录扫描web超时修改无效

### ISSUE THREAD

**Issue by chencicici** [TideSec/TscanPlus#168]
![image](https://github.com/user-attachments/assets/38673a93-4ef0-40d0-829d-07893e2655ea)
修改后保存不生效
![image](https://github.com/user-attachments/assets/60718481-c834-4376-b99a-4cae707e6f08)

**Comment by VBPush** [comment]
对的，我也遇到这个问题了

**Comment by TideSec** [comment]
感谢两位师傅，v2.6.2已经修复该问题，下个版本会更新上。
<img width="383" alt="image" src="https://github.com/user-attachments/assets/e7d0242c-f0af-4cdd-90fb-cd3dcd15bb41">
