### ISSUE TITLE
内网扫描打印机疯狂吐纸问题

### ISSUE THREAD

**Issue by dongluliang** [TideSec/TscanPlus#169]
建议默认屏蔽9100端口，部分打印机被扫描该端口会疯狂吐纸。

**Comment by dongluliang** [comment]
9100、631 和 515 端口 建议屏蔽这三个，或增加扫描可选项“是否扫描打印机端口”。

**Comment by dongluliang** [comment]
或从top100和top1000端口中删除9100端口。

**Comment by TideSec** [comment]
感谢师傅，后面会考虑增加个选项。
