### ISSUE TITLE
WebShell的URL编码,双重URL编码，以及Base64编码存在问题

### ISSUE THREAD

**Issue by cllwlaq** [TideSec/TscanPlus#170]
红队常用工具---->WebShell编码的功能块，这个地方URL编码和双重URL编码会将所有内容都编码了，会分不清哪个是需要的一句话木马，应该优化为只编码一句话木马；同时Base64编码也根本没有对一句话木马进行编码
![URL](https://github.com/user-attachments/assets/12abcfe0-abdf-4745-9103-c834726a0c91)
![Double URL](https://github.com/user-attachments/assets/83bffcf6-4cf1-4a5e-86e0-0f4ae975bac3)
![Base64](https://github.com/user-attachments/assets/46215b86-5cfc-4997-9203-1e239fece1f0)

**Comment by TideSec** [comment]
这个主要是前端展示的问题，框架有点小bug，不过这个编码在这里用到的比较少，需要用的话可以在编码转换模块。
