### ISSUE TITLE
端口扫描扫描漏掉一些端口

### ISSUE THREAD

**Issue by dtset001** [TideSec/TscanPlus#172]
我测试过几次都是这样，我这里遇到一个1433端口，http协议，是一个正常网站，但是就是扫不出来.

**Comment by TideSec** [comment]
> 我测试过几次都是这样，我这里遇到一个1433端口，http协议，是一个正常网站，但是就是扫不出来.

师傅方便提供下ip地址，测试看看么，如果是常规web的话应该能识别到
