### ISSUE TITLE
自动退出

### ISSUE THREAD

**Issue by muyuzhihzou** [TideSec/TscanPlus#174]
可能是资产添加的比较多，或者线程开的比较大。经常在开始端口开放扫描时自动退出软件，再次启动软件后需要重新执行任务。
执行中的任务在退出软件或中断后不保存执行进度，下次打开软件时只能重新从头运行，建议加入进度保存，当再次启动软件时可在项目管理处点击继续执行。

**Comment by TideSec** [comment]
资产过多可能导致内存不足，从而被系统kill掉。你是添加了ip还是域名，有多少资产？
目前进度保存只是针对单个功能的，对整个项目还没法进行进度恢复。

> 可能是资产添加的比较多，或者线程开的比较大。经常在开始端口开放扫描时自动退出软件，再次启动软件后需要重新执行任务。 执行中的任务在退出软件或中断后不保存执行进度，下次打开软件时只能重新从头运行，建议加入进度保存，当再次启动软件时可在项目管理处点击继续执行。

**Comment by TideSec** [comment]
可以试试最新版本，如果还没有解决，可以再提issue.
