### ISSUE TITLE
JWT模块alg=None算法支持建议

### ISSUE THREAD

**Issue by nonu11** [TideSec/TscanPlus#176]
当使用alg=none签名绕过生成payload时，不支持none算法，建议增加None算法支持，方便生成payload。

![图片](https://github.com/user-attachments/assets/339c0f66-c072-482b-9014-71b39f2f8305)

**Comment by TideSec** [comment]
感谢师傅反馈，下个版本v2.6.2已经增加none算法，致谢名单+1
<img width="1118" alt="image" src="https://github.com/user-attachments/assets/f5db156d-e6c9-4089-a763-377c054c2daf">
