### ISSUE TITLE
弱口令rdp扫描数量大的时候闪退

### ISSUE THREAD

**Issue by passevery** [TideSec/TscanPlus#177]
弱口令rdp扫描数量大的时候闪退

**Comment by TideSec** [comment]
师傅扫了多少资产会出现闪退的情况？

**Comment by passevery** [comment]
二三百个



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月22日 17:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [TideSec/TscanPlus] 弱口令rdp扫描数量大的时候闪退 (Issue #177) |

师傅扫了多少资产会出现闪退的情况？

**Comment by TideSec** [comment]
从互联网上找了几千个，没发现闪退，师傅方便邮箱发下资产么？

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/d763249a-c71c-48d0-854a-3f13dfaccd73" />

**Comment by passevery** [comment]
感谢作者的辛苦付出。就那几天闪退比较多，后来就没有了

**Comment by TideSec** [comment]
好的，后续有Bug可以再反馈，感谢师傅。
