### ISSUE TITLE
版本v2.60代理未能成功保存及问题情况

### ISSUE THREAD

**Issue by GualaoXiaoLaji** [TideSec/TscanPlus#178]
1.项目中设置好代理http://127.0.0.1:7777,保存运行，点击编辑，打开高级配置后，看不见原本配置的代理信息
![image](https://github.com/user-attachments/assets/7c0eb745-ad72-4f72-8b7a-1c781507e7c6)

2.代理配置用到的是2024年9月2日 Tide安全团队公众号发的文章中使用说到HTTP和HTTPS两种协议配置，使用不成功，使用配置的代理日志记录当中并没有相关日志，建议设置三个协议输入框，HTTP，HTTPS，SO，等并且配置验证协议配置成功Proxifier的一样有一个验证功能

这个是我遇到的问题和所给出建议，

**Comment by TideSec** [comment]
这里的代理地址是全局的，设置后只要保存了，再打开应该还会有，丢失的话是不是配置文件有问题或者代理格式异常导致的？
<img width="540" alt="image" src="https://github.com/user-attachments/assets/867edac8-1bfe-4400-af28-ca6313e94f90">
至于代理验证问题，后面计划加个代理池功能，到时候会把这些考虑上，感谢师傅。
