### ISSUE TITLE
关于空间测绘功能的问题

### ISSUE THREAD

**Issue by qty567** [TideSec/TscanPlus#181]
首先这个搜索好像有延迟bug，就比如我搜的是1，它没出结果，但我搜2的时候又跳出来1的结果。其次就是对搜索引擎语法支持的不太全，在自定义字段中，我用quake引擎试了一下domain:"360.cn"、cert:"baidu.com"等语法均没搜索出结果。个人感觉这种用字段搜索的方式不太好用，还不如直接就改成用正常的语法搜索，然后可以在旁边给出搜索引擎常用的语法提示，这样既简单又好查，这边其实可以参考一下你们赞助的密探工具。

**Comment by TideSec** [comment]
搜索是需要等一会的，特别是结果比较多的时候，每次请求api会间隔一秒。
quake的自定义的确有双引号转义的问题，下个版本已经修复，感谢师傅反馈。
