### ISSUE TITLE
端口扫描能否设置只识别服务指纹，不识别Web指纹

### ISSUE THREAD

**Issue by YS11i** [TideSec/TscanPlus#184]
端口扫描能否设置只识别服务指纹，不识别Web指纹

**Comment by Fanc1er** [comment]
部分服务指纹存在不识别情况，是否添加可FingerprintHub类似的规则自行添加服务指纹

**Comment by TideSec** [comment]
> 端口扫描能否设置只识别服务指纹，不识别Web指纹

可以关闭这里的端口指纹选项，这样就不会探测指纹。或者在url探测中，将指纹规则设置为最小，这样能大大提升效率。
<img width="463" alt="image" src="https://github.com/user-attachments/assets/d82ab363-15cf-49ff-9c01-af95f5f4e294">

**Comment by TideSec** [comment]
> 部分服务指纹存在不识别情况，是否添加可FingerprintHub类似的规则自行添加服务指纹

添加自定义指纹可以参考这个。
<img width="897" alt="image" src="https://github.com/user-attachments/assets/04b3883d-0225-4adc-9387-45b2b01f82bb">

**Comment by Fanc1er** [comment]
上述的描述添加指纹属于web服务指纹，添加的端口扫描时的服务识别指纹，tcp类型或者udp类型的服务指纹，例如：Apache RocketMQ ，
<img width="1330" alt="image" src="https://github.com/user-attachments/assets/93f936bd-2927-4c1f-b1f1-7474dfcd78dc">
<img width="1289" alt="image" src="https://github.com/user-attachments/assets/f091ba5f-7b84-479e-9b61-c8363473b0ef">
