### ISSUE TITLE
红队常用命令添加有误

### ISSUE THREAD

**Issue by sourcexu7** [TideSec/TscanPlus#186]
![image](https://github.com/user-attachments/assets/343329dd-0a2e-4049-8a7c-28e5df1d6e66)
编辑的时候是有一句话木马的，保存再看就没了
![image](https://github.com/user-attachments/assets/2935b259-6fb5-4669-a632-7e1a622c3c7b)

**Comment by TideSec** [comment]
感谢师傅反馈，下个版本v2.6.2已修复，是因为特殊字符转码问题导致显示异常。
