### ISSUE TITLE
爆破存在一些缺陷

### ISSUE THREAD

**Issue by huaiyi255** [TideSec/TscanPlus#188]
![图片](https://github.com/user-attachments/assets/1f1d10d3-37b0-4239-aa93-3130abb28510)
问题1，目标输入的地方可以让他不管输入是什么都可以从中提取ip并输出，不然可能某个地方多一个字符就会如下报错
![图片](https://github.com/user-attachments/assets/4b95095e-77d3-4d7f-a0f3-2832d1cc4bd6)
问题2，工具虽然存在很多默认字典，但是能不能添加一个自定义用户名的功能，不管爆破什么最好都可以自定义用户名
![图片](https://github.com/user-attachments/assets/a621a8c1-7c09-4725-b982-d878c4504a04)

**Comment by huaiyi255** [comment]
还有能不能问一下爆破的逻辑，因为有些爆破工具是 先判断ip存活之后再爆破，但是有些ip是禁ping的 会漏爆破很多资产。还有爆破能不能识别一下，对方已经禁止你访问爆破了，就跳过爆破

**Comment by huaiyi255** [comment]
还有一个问题，在爆破大概10个资产的端口 字典是500*5000时，会偶尔卡住不动很长时间

**Comment by TideSec** [comment]
问题1：“某个地方多一个字符就报错”这个是输的什么字符？正常来说只要是每行一个ip地址，就算有一行错了，应该也不影响其他的扫描。
问题2：目前的默认用户名字典是根据各种服务来针对性收集的，如果想自己定义，可以直接在config/CrackDict目录下的字典文件中直接修改。

**Comment by TideSec** [comment]
> 还有能不能问一下爆破的逻辑，因为有些爆破工具是 先判断ip存活之后再爆破，但是有些ip是禁ping的 会漏爆破很多资产。还有爆破能不能识别一下，对方已经禁止你访问爆破了，就跳过爆破

目前逻辑是直接判断端口是否开放，不会使用ping判断，端口开放后会进行指纹服务识别，然后进行爆破，爆破的时候会根据返回标识来判断是否禁止爆破。

**Comment by TideSec** [comment]
> 还有一个问题，在爆破大概10个资产的端口 字典是500*5000时，会偶尔卡住不动很长时间

这个应该和服务有关系，有些服务响应比较慢，比如ftp之类的，像ssh之类的比较快。
