### ISSUE TITLE
端口数与队列数统计异常

### ISSUE THREAD

**Issue by zhuanyedecainiao** [TideSec/TscanPlus#189]
扫描1个IP的全端口，队列65535个，扫描结果94189个
![image](https://github.com/user-attachments/assets/bb43c640-0df5-4b2f-a3cd-2cd15638d10b)

**Comment by TideSec** [comment]
你这个应该是第一次扫描没完全结束，你又执行了第二次扫描，导致计数有点bug，这个涉及前后端同步，目前还没解决好。
