### ISSUE TITLE
端口扫描问题21端口开放

### ISSUE THREAD

**Issue by HuanYues** [TideSec/TscanPlus#194]
大量的测试发现，直接都关机了的服务器 再禁ping扫描的状态下，也能扫描出21端口开放的情况。
发现基本上禁ping扫描模式都会扫出21端口开放，不管任何服务器IP地址大多数都会如此。
![image](https://github.com/user-attachments/assets/3252a1ad-c9f2-4e8e-aaf6-7d83d276ac40)

**Comment by HuanYues** [comment]
补充：这些主机检查发现都并没有开放内外网的21端口

**Comment by TideSec** [comment]
出现这种现象有几种情况
1、可能你电脑有杀软，比如火绒之类的，可能导致扫描端口时某些端口会显示一直开放
2、网络问题，比如光猫或运营商的一些策略，可以切下热点试一下
3、电脑问题，比如使用过代理之类的，也可能出现这情况，可以重启电脑再试下
