### ISSUE TITLE
扫描本机或者虚拟机的时候无结果

### ISSUE THREAD

**Issue by chensec0510** [TideSec/TscanPlus#195]
![PixPin_2024-11-26_11-01-40](https://github.com/user-attachments/assets/2bba6b84-4e90-449e-a973-71061903e590)

单独去做端口扫描模块是有结果的，但是以项目形式去扫，没有结果。应该不是配置的问题吧

**Comment by TideSec** [comment]
看配置没问题，我试了下本机扫本机没什么问题的，项目形式扫其他目标应该没问题吧

> 单独去做端口扫描模块是有结果的，但是以项目形式去扫，没有结果。应该不是配置的问题吧

**Comment by chensec0510** [comment]
我刚试了下，不仅仅是本机IP，连其他目标都是这个情况

**Comment by chensec0510** [comment]
![image](https://github.com/user-attachments/assets/a5a4a246-4c3f-4610-bf0e-01799b971701)
日志也没报错呢，不到1秒就结束了

**Comment by chensec0510** [comment]
![image](https://github.com/user-attachments/assets/fc674b03-b93d-4379-ba86-09a3130fdef8)
看日志也没报错，不到一秒就已经结束任务了

**Comment by TideSec** [comment]
是不是因为你扫描的目标禁ping了，所以没探测到存活，你把ping扫描关掉试下

**Comment by chensec0510** [comment]
噢噢，是这个问题，已经好了。3Q
