### ISSUE TITLE
【oracle 爆破问题

### ISSUE THREAD

**Issue by charis3306** [TideSec/TscanPlus#196]
【oracle 爆破问题】 https://www.bilibili.com/video/BV1R7z5YKEXN/?share_source=copy_web&vd_source=d8b3401c69e95f347bd42cee04d6a532

**Comment by TideSec** [comment]
感谢师傅反馈，还录了个详细的视频。
oracle一直是用的docker环境测试的，看你是用的win，你oracle是用的哪个版本，有下载地址么，我安装试下~

**Comment by charis3306** [comment]
【有道云笔记】Oracle windows 数据库搭建.md
https://note.youdao.com/s/aeydrwPX

**Comment by TideSec** [comment]
感谢师傅的视频和参考文档，经测试，是因为“仅破解一个账户”的选项没传到后台，所以每次只破解一个密码。v2.6.6已经修正，可在需要时私信或公众号后台获得一个Key。

<img width="574" alt="image" src="https://github.com/user-attachments/assets/c8babecf-2102-487b-9b4f-bf9b87066925" />

另外关于sys和system的问题，我也遇到了，我本地也没法登录sys账号，但比较诡异的是sys的确可以远程连接，通过连接命令也能看到能获取到数据库信息。比如都执行 select * from v$version  但有些命令比如 select * from user_role_privs 返回差别还不小。

<img width="812" alt="image" src="https://github.com/user-attachments/assets/4b51ca98-d6af-4066-bb2b-2359afdb9802" />


<img width="748" alt="image" src="https://github.com/user-attachments/assets/9ceeda9a-1cac-44aa-9816-f1ad682b9cd4" />

**Comment by charis3306** [comment]
感谢您的反馈和修正！我已经测试过了，确实是因为“仅破解一个账户”选项没有正确传到后台，导致每次只破解一个密码。非常感谢您在V2.6.6版本中已经解决了这个问题，真是太及时了！

另外，我非常感谢您为网络安全领域所作出的贡献。您的软件对很多从事渗透测试和安全研究的人来说非常有帮助，尤其是您提供了免费的版本，这无疑极大地推动了我们整个行业的发展。衷心感谢您的付出和分享！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

________________________________
发件人: 重剑无锋 ***@***.***>
发送时间: Friday, December 20, 2024 3:09:18 PM
收件人: TideSec/TscanPlus ***@***.***>
抄送: charis ***@***.***>; Author ***@***.***>
主题: Re: [TideSec/TscanPlus] 【oracle 爆破问题 (Issue #196)


感谢师傅的视频和参考文档，经测试，是因为“仅破解一个账户”的选项没传到后台，所以每次只破解一个密码。v2.6.6已经修正，可在需要时私信或公众号后台获得一个Key。

image.png (view on web)<https://github.com/user-attachments/assets/c8babecf-2102-487b-9b4f-bf9b87066925>

另外关于sys和system的问题，我也遇到了，我本地也没法登录sys账号，但比较诡异的是sys的确可以远程连接，通过连接命令也能看到能获取到数据库信息。比如都执行 select * from v$version 但有些命令比如 select * from user_role_privs 返回差别还不小。

image.png (view on web)<https://github.com/user-attachments/assets/4b51ca98-d6af-4066-bb2b-2359afdb9802> image.png (view on web)<https://github.com/user-attachments/assets/9ceeda9a-1cac-44aa-9816-f1ad682b9cd4>

―

**Comment by TideSec** [comment]
好的，后续有其他bug可以再反馈，感谢师傅认可和支持。
