### ISSUE TITLE
MemCached未授权 连接提示的命令错误

### ISSUE THREAD

**Issue by Derrrry** [TideSec/TscanPlus#200]
![3fadddefa74f47a1b71d8ca46267a2e](https://github.com/user-attachments/assets/a10c5c54-d403-4b0c-b224-2f3a0c984df1)
![5c7adb913de2b986ded4e40d5d0e3eb](https://github.com/user-attachments/assets/6126f798-eb60-4fd7-b29a-2b1bbb953ab5)
![38137baef5a05949d35e00ef168677f](https://github.com/user-attachments/assets/7f16d34a-95ca-46de-8784-a41eee096e1e)
![c216dbb6368748d2efea2f0d91e90e8](https://github.com/user-attachments/assets/f621610c-ef76-4a86-b008-ac6f772e8fdf)
应该是stats而不是status

**Comment by TideSec** [comment]
好的，感谢师傅，下个版本已修复，致谢名单+1
