### ISSUE TITLE
IP归属地查询，qqwry.dat文件加载bug

### ISSUE THREAD

**Issue by qingchenhh** [TideSec/TscanPlus#201]
IP归属地查询，提示IP查询库尚未初始化，config目录下缺失qqwry.dat文件，可删除cfgversion.txt文件后重启程序，程序会自动重新下载配置文件。
![image](https://github.com/user-attachments/assets/27188bd5-ac6e-420a-9a74-164064d21b86)

config目录下是存在qqwry.dat文件。
![image](https://github.com/user-attachments/assets/6362eefb-42eb-4814-8d01-e4b6f143ec3b)

**Comment by TideSec** [comment]
应该是第一次运行，qqwry.dat文件刚下载完，需要重启程序即可

**Comment by qingchenhh** [comment]
> 应该是第一次运行，qqwry.dat文件刚下载完，需要重启程序即可

好的

**Comment by TideSec** [comment]
下个版本加了个二次加载，感谢师傅~
