### ISSUE TITLE
建议在“密码破解”中增加对资产IP的有效性验证

### ISSUE THREAD

**Issue by hkylin** [TideSec/TscanPlus#202]
建议在“密码破解”中增加对资产IP的有效性验证：有时手贱输IP多输了数字，程序没报错提示，等半天才看结果发现输错了..
![QQ截图20241202165949](https://github.com/user-attachments/assets/8b0ca8a9-68f9-4cbf-9ea6-ac3fb406f36a)
![QQ截图20241202170125](https://github.com/user-attachments/assets/e44f098e-951b-4461-a022-5b24e85ca72d)

**Comment by TideSec** [comment]
感谢师傅，下个版本加了个提醒，致谢名单+1
<img width="1244" alt="image" src="https://github.com/user-attachments/assets/baf15ce9-912f-4393-9be0-faf0879214fe">
