### ISSUE TITLE
Mac m4芯片安装完提示  tscanplus已损坏 无法打开 你应该将它移到废纸篓 ，如何解决

### ISSUE THREAD

**Issue by sec404forbidden** [TideSec/TscanPlus#204]

**Comment by TideSec** [comment]
可以查看 https://github.com/TideSec/TscanPlus?tab=readme-ov-file#faq
<img width="860" alt="image" src="https://github.com/user-attachments/assets/223fd58a-bca8-4a69-892f-2b1a717bd806">
