### ISSUE TITLE
tscanplus 每次扫描完数据归类问题

### ISSUE THREAD

**Issue by sec404forbidden** [TideSec/TscanPlus#205]
每个功能点 每次扫描完 ，不会单独生成一个扫描的result文件，每次扫描都会留存上一次扫描的结果，在多个内网环境使用时，如果IP重复，会导致数据混淆，数据叠加，无法区分，希望每次扫描完，结果生成一个单一的扫描结果，重新打开建立任务时，每个功能点是不包含上次的结果的。

**Comment by TideSec** [comment]
你是说哪个功能？ip和url探测之类的每次扫描都会清空之前的数据再扫描的，怎么会出现数据混淆的情况？
或者你用下新建一个空项目，每个环境都用不同项目文件，这样能解决你的问题么

**Comment by sec404forbidden** [comment]
做内网的时候，不同单位，内网地址可能重复，可以新建单个项目这样是最好的，不同项目分类，可以避免问题，刚发现，开头有的，我一直default使用，感谢。

**Comment by TideSec** [comment]
感谢师傅~
