### ISSUE TITLE
Kali下 2.6.0 界面上点升级到 2.6.3 ，进度条走完后依然2.6.0。

### ISSUE THREAD

**Issue by Finback** [TideSec/TscanPlus#210]
Kali下 2.6.0 界面上点升级到 2.6.3 ，进度条走完后依然2.6.0。看到下载的新文件没替换成功就删除了

**Comment by TideSec** [comment]
感谢反馈，目前针对liux的因为打包比较麻烦，只有大版本才打包linux版的，小版本的没打包。正常是不应该提示升级的，后面版本修复这个问题了。
