### ISSUE TITLE
下载命令下的OS类型有两个ALL

### ISSUE THREAD

**Issue by cream-sec** [TideSec/TscanPlus#214]
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/bee8caf3-4b87-4f80-9d96-6e16810e4b7d">

**Comment by TideSec** [comment]
感谢师傅，v2.6.6将修复这个bug，致谢+1
凭截图和ID，可在需要时私信或公众号后台获得一个Key。

<img width="520" alt="image" src="https://github.com/user-attachments/assets/99e57afb-35e7-4cad-b036-2346cc8adc55" />
