### ISSUE TITLE
Mac环境下，想删除项目，项目选择框无法选中

### ISSUE THREAD

**Issue by c0okB** [TideSec/TscanPlus#217]
Mac环境下，想删除项目，项目选择框无法选中
<img width="782" alt="WX20241217-160145@2x" src="https://github.com/user-attachments/assets/2afec21d-933a-4e92-a4b5-23c58b8f6880" />

**Comment by TideSec** [comment]
Default项目是默认的，只能清空内容，但无法删除，因为删除后会影响其他功能。
<img width="1198" alt="image" src="https://github.com/user-attachments/assets/f5e9c333-a6ec-463d-b593-cf9f247b5a44" />
