### ISSUE TITLE
端口扫描处直接选择全端口并不是1-65535端口

### ISSUE THREAD

**Issue by 1024548219** [TideSec/TscanPlus#219]
直接打开默认是TOP100端口
<img width="980" alt="1" src="https://github.com/user-attachments/assets/866e099f-0c83-4c70-895f-bb1782c1081b" />
选择全端口后端口并未发生变化
<img width="990" alt="2" src="https://github.com/user-attachments/assets/37f62b45-9761-43ab-bfcc-10cd124f8555" />
必须再次选择其余选项后选回来才可以变为1-65535
<img width="980" alt="3" src="https://github.com/user-attachments/assets/9a33d277-66d3-492e-a006-203cd5e3dc4b" />

**Comment by TideSec** [comment]
的确存在这个问题，下个版本v2.6.6已修复，感谢师傅。
<img width="534" alt="image" src="https://github.com/user-attachments/assets/8def24df-1303-49c7-b160-70f4a5247a09" />
