### ISSUE TITLE
目录扫描功能闪退

### ISSUE THREAD

**Issue by Zxc123456zxc** [TideSec/TscanPlus#22]
使用目录扫描功能直接闪退，而且导入字典，行数15322行，但是显示导入的字典行数为248618，最大支持10万行
![image](https://github.com/TideSec/TscanPlus/assets/63491799/bc25f84b-cbf2-4e76-88c2-f4090253dc4e)
![image](https://github.com/TideSec/TscanPlus/assets/63491799/6c51625d-066b-43bf-87bc-3dab54bab699)

**Comment by Zxc123456zxc** [comment]
windows版本

**Comment by TideSec** [comment]
感谢师傅反馈，这个bug在v1.1版本已经修复，元旦前后会发一版。
