### ISSUE TITLE
版本更新问题

### ISSUE THREAD

**Issue by cream-sec** [TideSec/TscanPlus#223]
版本更新的时候，点击“开始更新”之后等待下载更新完毕，待更新成功点击“立即安装”。
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/97ca19f3-707b-47d7-930a-ba3be70e900b" />

等安装完毕发现软件版本没有变化！
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/44fa7aca-12f5-4a79-b7e6-b0083960f2b6" />

**Comment by TideSec** [comment]
这个是2.6版本刚加了自动更新功能时有点Bug，是因为你的exe文件名带了版本号而自动升级程序的exe不带版本号，2.6.2之后就没这个问题了。
