### ISSUE TITLE
空间测绘--zoomeye报错401

### ISSUE THREAD

**Issue by git-zl** [TideSec/TscanPlus#227]
报错内容zoomeyeapi Warning: unexpected status code 401 received from https://api.zoomeye.org/web/search?query=site:xx.com&s=1000&page=1

![401](https://github.com/user-attachments/assets/c131621e-f2eb-4a27-9833-87432608b0a8)

**Comment by TideSec** [comment]
![image](https://github.com/user-attachments/assets/2fe3c07a-8a9b-4c69-af13-cb43bc0f1b49)
接口没问题，可能是你apikey的问题

**Comment by git-zl** [comment]
<img width="1121" alt="1" src="https://github.com/user-attachments/assets/581dc6f3-c538-4a4d-88c0-5ab687716134" />
<img width="992" alt="2png" src="https://github.com/user-attachments/assets/496a1922-8e83-4f13-9182-5e02489c2188" />

<img width="992" alt="3png" src="https://github.com/user-attachments/assets/31fa051d-2695-47d3-8d49-7355877d88ce" />
用的是同一个key，你们这边可以吗？

**Comment by git-zl** [comment]
可以了，重新下载了一下
