### ISSUE TITLE
v1.2版本smb协议主机名

### ISSUE THREAD

**Issue by hunmeng123** [TideSec/TscanPlus#25]
![TscanPlus](https://github.com/TideSec/TscanPlus/assets/68940856/d6700672-4860-45e7-ad67-5b775ffe75ce)

**Comment by hunmeng123** [comment]
主机名乱码

**Comment by TideSec** [comment]
互联网地址么，能提供下地址我看下么，微信secplus

**Comment by hunmeng123** [comment]
内网地址

**Comment by TideSec** [comment]
感谢反馈，bug已经记录，致谢名单+1~
