### ISSUE TITLE
一些OA还是识别出不来

### ISSUE THREAD

**Issue by wlaq-su** [TideSec/TscanPlus#26]

**Comment by TideSec** [comment]
是哪个OA，有具体名称和地址么
TscanPlus为了精简指纹库，所以把大约2/3的不常用指纹给去掉了，后期会把指纹都加进来~

**Comment by TideSec** [comment]
感谢师傅反馈，后续会继续完善指纹和高危目录主动探测的功能，师傅可以加下交流群~
