### ISSUE TITLE
【BUG】url 探测功能-导入大量 url 扫描时卡死

### ISSUE THREAD

**Issue by impdx** [TideSec/TscanPlus#27]
环境：macbook m3pro 
操作系统：macos14.1 
内存：18g
cpu：apple M3pro

url 探测 2100 条左右，线程 50，gui 卡死

希望可以修复一下，试了 3 次，20 /50/100线程都卡死

**Comment by impdx** [comment]
2 线程 gui 正常，但 20 就会 gui 卡死

**Comment by impdx** [comment]
2 线程下达到 1900 条左右 gui 会变得很卡，肉眼可见

**Comment by TideSec** [comment]
感谢师傅反馈，及提供具体场景，下个版本会优先修复，致谢名单+1~
