### ISSUE TITLE
TscanPlus交流反馈群~

### ISSUE THREAD

**Issue by TideSec** [TideSec/TscanPlus#28]
交流群已满，暂时不再新建交流群。

**Comment by jiangyuening** [comment]
直接显示应用程序“TscanPlus_darwin_amd64_v1.2”无法打开。。。。

**Comment by relishmylife** [comment]
过期了，哥哥

**Comment by TideSec** [comment]
> 过期了，哥哥

已更新，超过200人就停止进群了~

**Comment by sriver-song** [comment]
怎么进群呢，二维码过期了，还考虑扩员吗？

**Comment by TideSec** [comment]
> 已更新，超过200人就停止进群了~

已更新，超过200人就停止进群了~

**Comment by 80576560** [comment]
网络空间测绘，众多接口，查询结果会去重吗

**Comment by TideSec** [comment]
> 网络空间测绘，众多接口，查询结果会去重吗

目前是根据url、ip、端口三个参数对结果进行去重。

**Comment by 80576560** [comment]
![image](https://github.com/TideSec/TscanPlus/assets/41313763/12c3b36a-7340-4675-a5c0-e27b2782712a)

网络空间测绘  zoomeye拼接地址有问题   http后面忘了加冒号

**Comment by 80576560** [comment]
![image](https://github.com/TideSec/TscanPlus/assets/41313763/6baf6d87-f217-474f-b9e4-27f60b1c95f4)
网络空间测绘  zoomeye拼接地址有问题   http后面没冒号

**Comment by TideSec** [comment]
> 网络空间测绘 zoomeye拼接地址有问题 http后面没冒号

目前1.5版已经修复该问题

**Comment by Reach-Z** [comment]
有linux版本吗，想要linux版

**Comment by TideSec** [comment]
> 有linux版本吗，想要linux版

1.7或1.8计划会打包linux版的

**Comment by ymbzd** [comment]
师傅 社工字典生成还需要优化一下  例如输入  wanglei    出来的字典没有  wanglei@1234这种弱口令

**Comment by li-baige** [comment]
新版本1.8目录扫描无结果，加上代理也看不到结果

**Comment by TideSec** [comment]
> 十分感谢大佬，感觉还可以加点加解密功能，（aes，des，spring配置文件解密之类的）没外网环境的时候可以派上用场，大佬可以考虑下，只是个建议~

这个后面有规划，暂时还没做。

**Comment by TideSec** [comment]
> 新版本1.8目录扫描无结果，加上代理也看不到结果

我测试正常，师傅能贴个图或者给个url，我测试一下

**Comment by TideSec** [comment]
> 师傅 社工字典生成还需要优化一下 例如输入 wanglei 出来的字典没有 wanglei@1234这种弱口令

好的，回头我再完善一下字典。
