### ISSUE TITLE
开启扫描时切换到其他功能界面重叠

### ISSUE THREAD

**Issue by y1u0ws** [TideSec/TscanPlus#29]
![4e64b234f8266ee7432b76d02aec14a](https://github.com/TideSec/TscanPlus/assets/41445912/dfdd936a-5837-4da8-be97-4ad50b977392)

**Comment by TideSec** [comment]
第一次见到这个反馈，可能是有扫描任务，数据结果较多，导致前端卡死了，现在1.3版本已经对数据进行了分页展示，应该能解决这个问题。过段时间会发布。
