### ISSUE TITLE
下载了TscanPlus_darwin_arm64_v1.2.zip，解压，m1机器，打开提示文件已损坏

### ISSUE THREAD

**Issue by lonycc** [TideSec/TscanPlus#31]
RT，解压后TscanPlus_darwin_arm64_v1.2.app 大小为 47.2MB

**Comment by TideSec** [comment]
查看最下面的FAQ，MAC的问题都能解决。
<img width="903" alt="image" src="https://github.com/TideSec/TscanPlus/assets/46297163/3465ceff-993b-4db7-ad2a-29cfc25c5f55">
