### ISSUE TITLE
url探测导出结果时报错

### ISSUE THREAD

**Issue by Huck-Lim** [TideSec/TscanPlus#38]
![image](https://github.com/TideSec/TscanPlus/assets/36686730/aca72d75-c3ab-4266-947e-c52292b00367)
操作系统：windows10
扫描url数量4732
一开始以为是中文名的原因，后面改成纯英文的，还是报错。

**Comment by TideSec** [comment]
你url任务第一条有特殊字符么？就是你打码的那部分。师傅可以加下群，具体沟通一下~

**Comment by Huck-Lim** [comment]
目前仅发现存在大量-号和小部分#号

**Comment by Huck-Lim** [comment]
> 你url任务第一条有特殊字符么？就是你打码的那部分。师傅可以加下群，具体沟通一下~

打码的部分没有特殊字符。好像多了一个空格，但是我排查了，我输入的url是没有空格的
![image](https://github.com/TideSec/TscanPlus/assets/36686730/40f5fa89-f454-4d4b-832e-fdb4a1f4f0a5)

**Comment by Huck-Lim** [comment]
第一行url后面自带的/导致的导出问题，删除即可

**Comment by TideSec** [comment]
> 第一行url后面自带的/导致的导出问题，删除即可

好的，回头我也对/做个转移。上面多的一个空格，就是把一些特殊字符替换成下划线了~
