### ISSUE TITLE
目录fuzz

### ISSUE THREAD

**Issue by lsadaharu** [TideSec/TscanPlus#4]
师傅这个位置的默认fuzz列表重复了u，少了r
![image](https://github.com/TideSec/TscanPlus/assets/50976099/8dec123b-e7a5-436b-94ba-6f11e358246c)

**Comment by TideSec** [comment]
拜谢，想问下你是怎么能发现这个的，太不可思议。。   o(╥﹏╥)o

**Comment by lsadaharu** [comment]
哈哈哈，因为我之前用御剑的fuzz发现了相同的错误

**Comment by TideSec** [comment]
下个版本已经更正，枚举速率也有了大大提升。感谢~
