### ISSUE TITLE
建议：可以增加一个前端JS收集的查询，然后与目录扫描功能结合拼接起来路径，然后进行状态探测，可以事半功倍

### ISSUE THREAD

**Issue by Kteng-723** [TideSec/TscanPlus#47]
建议：可以增加一个前端JS收集的查询，然后与目录扫描功能结合拼接起来路径，然后进行状态探测，可以事半功倍
像一些JSfind的这种插件跑出来的地址路径，我们再一个一个手测比较麻烦，而且耗费时间，可以把他跟目录扫描的功能放在一起，然后结合在一起拼接路径，相当于给一个网址后，搜寻到前端的JS路径地址什么的，然后拆除拼接全部打包到目录扫描里探测，可以说省去大部分手测的时间，望采纳

**Comment by WasteMaterial** [comment]
臣附议🙋‍

**Comment by TideSec** [comment]
1.6版本已经实现，URLFinder功能。
