### ISSUE TITLE
建议:项目概览这里能否添加点击事件

### ISSUE THREAD

**Issue by WasteMaterial** [TideSec/TscanPlus#49]
![image](https://github.com/TideSec/TscanPlus/assets/32891131/788b0902-acf2-41ef-a181-71dd9afb8d75)
如图 
当有多个项目的情况下无法具体区分哪个项目存在敏感信息、漏洞的情况
建议添加一下功能 蟹蟹

**Comment by TideSec** [comment]
好的，后面会考虑加个提示~
