### ISSUE TITLE
Bug: 闪退

### ISSUE THREAD

**Issue by endin9** [TideSec/TscanPlus#50]
intel Mac 
OS 13.3.1 (22E261)
版本 v.16

问题描述：
端口扫描完成后，点击密码破解会闪退。
![image](https://github.com/TideSec/TscanPlus/assets/124877541/36582e1d-3456-4d3b-9ce3-fea267ad5ce3)

**Comment by TideSec** [comment]
感谢师傅，已经复现，1.7版修复~
