### ISSUE TITLE
Bug:爆破功能

### ISSUE THREAD

**Issue by wvykey** [TideSec/TscanPlus#51]
爆破功能在指定文件进行爆破时存在bug，单个密码可以爆破成功，但是多个密码爆破失败
版本：1.6
系统：windows10
截图如下：
![3](https://github.com/TideSec/TscanPlus/assets/132774343/581f01ab-c19a-49ef-b76e-574d068851cb)
![4](https://github.com/TideSec/TscanPlus/assets/132774343/57404596-9297-4e0d-a2bb-37625d7f4414)

**Comment by TideSec** [comment]
收到，感谢反馈，后面我复现看一下。

**Comment by TideSec** [comment]
1.7版本已经修复，支持对任意服务进行密码和用户名的字典自定义
