### ISSUE TITLE
密码破解mysql

### ISSUE THREAD

**Issue by xiaojj2021** [TideSec/TscanPlus#56]
密码破解太捞了 一点用没有
![image](https://github.com/TideSec/TscanPlus/assets/97785068/7ffdf0a1-e422-4aec-8f11-0f2417b5765a)
![image](https://github.com/TideSec/TscanPlus/assets/97785068/cf7c8e2c-af20-4eed-b0af-7aa9f0b8a339)
同样的环境下 没检测出来 无语

**Comment by TideSec** [comment]
感谢师傅反馈，刚看了下这个问题，主要是你这个test1用户稍微有点特殊，没有mysql表的权限，导致误报。我也试了下fscan、goby之类的，指定test1:test1账号密码，也没扫出来这个密码。
现在已经定位到该问题并优化代码，下个版本中已经修复，感谢反馈。
<img width="1220" alt="image" src="https://github.com/TideSec/TscanPlus/assets/46297163/5d9a167a-e64d-4bda-9b8f-395c35389eab">
