### ISSUE TITLE
Github接口api设置正确，可用验证时，显示无效

### ISSUE THREAD

**Issue by lsota1** [TideSec/TscanPlus#57]
![Snipaste_2024-05-11_14-14-18](https://github.com/TideSec/TscanPlus/assets/155864641/43b763d6-ad9e-47bd-85dc-0f5952df731f)
是这个接口配置时还需要加一些其它参数吗

**Comment by TideSec** [comment]
我测了下，应该是访问github网络的问题，国内经常被墙的缘故吧。
![2](https://github.com/TideSec/TscanPlus/assets/46297163/3d5de2fd-252d-4b70-8bf7-246967afc1cf)
开了代理就ok
![1](https://github.com/TideSec/TscanPlus/assets/46297163/a1034756-fb26-42d8-bc50-7ef42896c41e)
