### ISSUE TITLE
空间测绘中的Fofa对于免费版账户不可用

### ISSUE THREAD

**Issue by yuwan-jpg** [TideSec/TscanPlus#59]
{
   "errmsg" : "[820001] 没有权限搜索product字段",
   "error" : true
}

是否考虑判断没有权限查询的字段只查询有权限的

**Comment by TideSec** [comment]
程序中是做了两步判断，先发一个请求，如果报"没有权限搜索product字段"，就会使用普通账户的权限内查询字段进行查询。

**Comment by TideSec** [comment]
看了下普通用户，如果没有返回数据，应该是没有F币了。。

{"error":true,"errmsg":"[820031] F点余额不足"}
