### ISSUE TITLE
缺少linux版本

### ISSUE THREAD

**Issue by harry1080** [TideSec/TscanPlus#6]

**Comment by TideSec** [comment]
wails打包Linux版本有点麻烦，暂时没来得及打包。一般linux上都是命令行工具，可以用我的那个TideFinger_Go，功能都差不多。

**Comment by harry1080** [comment]
> wails打包Linux版本有点麻烦，暂时没来得及打包。一般linux上都是命令行工具，可以用我的那个TideFinger_Go，功能都差不多。

好的
