### ISSUE TITLE
密码破解模块的问题

### ISSUE THREAD

**Issue by FY036** [TideSec/TscanPlus#60]
作者密码破解模块有问题,我点击开始破解还没0.5秒300个请求就发完了,自己的服务器破解了7次才成功了一次,不准呀

**Comment by FY036** [comment]
ssh服务,其他的服务目前没试过

**Comment by TideSec** [comment]
v1.8版的ssh服务和telnet有点小Bug，1.9已经修复，交流群已发内测版，近期会发布正式版。
