### ISSUE TITLE
目录爆破的问题

### ISSUE THREAD

**Issue by FY036** [TideSec/TscanPlus#62]
很多网站用目录爆破功能都会封ip,感觉爆破目录功能的线程,延迟有问题像dos攻击一样,相同的网站我用dirsearch跑没问题

**Comment by TideSec** [comment]
能给出具体哪个网站么，我测试一下~  
这个功能大家用的还是比较多的，但你遇到的这种Bug还没遇到过，如果没有具体网站可能不太好复现。

**Comment by TideSec** [comment]
2.1版本的目录爆破已经进行了优化，可以再试一下。
