### ISSUE TITLE
您好，我这边好像遇到了一个bug

### ISSUE THREAD

**Issue by Myforever123** [TideSec/TscanPlus#64]
![1717157584111](https://github.com/TideSec/TscanPlus/assets/100850917/8a3419bc-cd17-4f7e-933f-09cda313baaa)
我扫描的是全端口，但队列数只有55，这是网站的问题吗

**Comment by TideSec** [comment]
这个是目标有安全防护设备，工具会有个检测机制，一旦检测到目标使用了防火墙或waf，这个时候检测任何端口都会显示存活，这时候就只检测最常见的55个端口。

**Comment by Myforever123** [comment]
原来如此，感谢分享这么棒的工具，祝您生活愉快！

**Comment by TideSec** [comment]
> 原来如此，感谢分享这么棒的工具，祝您生活愉快！

感谢支持~!
