### ISSUE TITLE
URL探测结果导出问题

### ISSUE THREAD

**Issue by badk1ng** [TideSec/TscanPlus#65]
当我扫描完URL存活之后，导出excel文件然后它提示文件名卷名无效等信息

![bug](https://github.com/TideSec/TscanPlus/assets/73769452/b301bcda-4679-460f-8c95-dae96992e5cc)

**Comment by TideSec** [comment]
应该是你的第一行url里面有特殊字符，或者url比较长导致的，下个版本已经控制文件名长度了。
