### ISSUE TITLE
我看工具有有效期，过期了还能用吗？是不是需要付费？

### ISSUE THREAD

**Issue by dracodong** [TideSec/TscanPlus#7]
<img width="567" alt="image" src="https://github.com/TideSec/TscanPlus/assets/36252282/40578ab5-acc9-4b83-be46-c58aa60a74c8">

**Comment by Ruqian01** [comment]
要是真好用，付费也可以接受，毕竟都要吃饭吗

**Comment by TideSec** [comment]
过期了会在github上再更新，这点不用担心。设个过期时间主要是想有新版本时，大家能更新一下，作者也能得到更多使用反馈，以便改进和维护。

**Comment by dracodong** [comment]
嗯嗯 付费也行。实际使用我看看效果，有bug反馈，希望这个工具可以更好的使用。
