### ISSUE TITLE
密码查询BUG

### ISSUE THREAD

**Issue by fitzxxx** [TideSec/TscanPlus#70]
功能点：辅助工具 -> 密码查询 -> 添加
BUG：添加新密码，点击保存后工具自带的密码会被覆盖。（应该需要追加写）
工具版本：v2.0
环境：Windows11 x64
![image](https://github.com/TideSec/TscanPlus/assets/162282048/afce0dbc-0128-442e-b0f0-c0ebd75c80b2)
![image](https://github.com/TideSec/TscanPlus/assets/162282048/0b50ef23-c3f8-4826-8c24-5b7028935a05)

**Comment by TideSec** [comment]
感谢师傅，2.1版本已经修复，致谢名单+1
