### ISSUE TITLE
端口扫描结束后自动闪退

### ISSUE THREAD

**Issue by DouLiYouTang31** [TideSec/TscanPlus#73]

**Comment by DouLiYouTang31** [comment]
疑似扫描队列过多自动闪退

**Comment by TideSec** [comment]
目前发现2.0在扫描RDP密码时，存在一定概率闪退，2.1版本已经修复。
如果不是RDP破解，那么可能是任务太多，导致CPU占用过高，系统没有可用资源导致卡死闪退，这种只能是降低线程了。
