### ISSUE TITLE
请问生成的枚举密码在什么文件夹，找不见下载的位置

### ISSUE THREAD

**Issue by didikakaka** [TideSec/TscanPlus#75]

**Comment by TideSec** [comment]
<img width="605" alt="image" src="https://github.com/TideSec/TscanPlus/assets/46297163/e23c3891-024b-455f-93f5-be600bb38f73">
点击旁边那个"打开字典目录"就可以看到生成的字典。
该目录默认是由"高级配置"-"导出目录"指定，在该目录下创建dict文件夹及相应字典文件。
