### ISSUE TITLE
希望增加资产测绘地址接口地址自定义,可能有时候会用到公司内网的 API

### ISSUE THREAD

**Issue by starscow** [TideSec/TscanPlus#80]
希望增加资产测绘地址接口地址自定义,可能有时候会用到公司内网的 API

**Comment by TideSec** [comment]
目前fofa支持自定义api地址，其他暂不支持。

如fofa需要使用自定义API接口，格式必须为 邮箱:key||url，在url和key之间为双竖线，示例如下：
629*****@qq.com:3f21a408*********6e3fa8078||http://fofaapi.com

<img width="960" alt="image" src="https://github.com/TideSec/TscanPlus/assets/46297163/e60bad05-c443-4ee3-8fc4-ae77645ad551">

**Comment by starscow** [comment]
我们是 hunter 希望可以也增加一些
