### ISSUE TITLE
Ubuntu22.04 Server 下报错

### ISSUE THREAD

**Issue by alex-dengx** [TideSec/TscanPlus#81]
DbFile: /opt/tscanplus/config/config.db
UserCfgDir: /opt/tscanplus/config
panic: failed to init GTK

goroutine 1 [running, locked to thread]:
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend.func1()
        github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:145 +0x139
sync.(*Once).doSlow(0x465449?, 0xc002ef84f5?)
        sync/once.go:74 +0xc2
sync.(*Once).Do(...)
        sync/once.go:65
github.com/wailsapp/wails/v2/internal/frontend/desktop/linux.NewFrontend({0x2418ce0, 0xc007dab560}, 0xc004c1a2c0, 0xc00436e558, 0xc0040b7650, {0x240ec20, 0xc007d73500})
        github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/linux/frontend.go:136 +0x77
github.com/wailsapp/wails/v2/internal/frontend/desktop.NewFrontend(...)
        github.com/wailsapp/wails/v2@v2.8.0/internal/frontend/desktop/desktop_linux.go:16
github.com/wailsapp/wails/v2/internal/app.CreateApp(0xc004c1a2c0)
        github.com/wailsapp/wails/v2@v2.8.0/internal/app/app_production.go:86 +0x5af
github.com/wailsapp/wails/v2/pkg/application.(*Application).Run(0xc007bb5a00)
        github.com/wailsapp/wails/v2@v2.8.0/pkg/application/application.go:58 +0x25
github.com/wailsapp/wails/v2.Run(0xc004c1a2c0?)
        github.com/wailsapp/wails/v2@v2.8.0/wails.go:14 +0x9a
main.main()
        TscanGui/main.go:37 +0x28f

**Comment by TideSec** [comment]
你这个是在图形化界面下执行的么？执行环境能截个图么
