### ISSUE TITLE
各位师傅大大,能不能给新版的套一层面杀,现在一下来就被微软杀死

### ISSUE THREAD

**Issue by aalhea** [TideSec/TscanPlus#82]
![image](https://github.com/TideSec/TscanPlus/assets/151757630/fb64c1b2-2b87-4be9-b827-f15932cb0ee1)
<img width="287" alt="微信图片_20240706224852" src="https://github.com/TideSec/TscanPlus/assets/151757630/6e18d7d6-0b60-4ab3-9316-5000f72d8783">

**Comment by TideSec** [comment]
这个没什么好办法，只能使用的时候暂停杀软了。因为就算做了免杀，过段时间还是会被查杀，但个人精力有限，目前主要还是在完善各功能，不可能一直和杀软较劲。
