### ISSUE TITLE
端口扫描问题

### ISSUE THREAD

**Issue by xing-t** [TideSec/TscanPlus#83]
端口扫描模块存在较大问题
1、开启icmp存活探测进行端口扫描，停止之后再次点击start发现存活的IP会少很多，存在不准确的情况
2、同样的IP扫描1000端口每次探测的结果都不一样只有针对单个IP进行扫描的时候结果会稍微准确一点
针对以上情况麻烦师傅帮忙解答一下，谢谢

**Comment by TideSec** [comment]
是不是线程开的太高导致的误报，建议ip端口扫描线程控制在200以下。
停止之后再次点击start是恢复上次扫描还是重新扫描？恢复上次扫描的话存活ip数量是针对未检测部分的，肯定会少。如果是重新扫描的话，理论上存活ip应该一样，如果有差距可能是线程太高导致。
