### ISSUE TITLE
目录扫描，字典问题

### ISSUE THREAD

**Issue by Zxc123456zxc** [TideSec/TscanPlus#84]
大佬，就行自己加载的字典，例如/page.asp，有 /  这个，那么扫描的时候就会出现两个  //  ，可以增加进行一个判断，如果不存在/自动加上，如果存在/，就默认不加，因为有的网站出现 两个 //  就不会返回信息，例如这个网站 ，只有一个 /就会返回信息
![image](https://github.com/user-attachments/assets/1c83253d-28b9-4e6f-b725-6da6f3c9c791)
如果是两个  // 就不会返回信息
![image](https://github.com/user-attachments/assets/2cfb2c6f-a76c-4e46-8129-d0e17ae9620c)

**Comment by TideSec** [comment]
感谢师傅，已经复现，后续会做统一处理，致谢名单+1
