### ISSUE TITLE
扫描任务

### ISSUE THREAD

**Issue by TAKAHASHI7** [TideSec/TscanPlus#86]
扫描任务会添加暂停选项吗，只有停止，停了之后需要重扫，导致结果也没有了
![微信截图_20240722153622](https://github.com/user-attachments/assets/3f4b8df5-a2b3-4959-af55-44f9014c4864)

**Comment by TideSec** [comment]
目前各子功能已经添加了暂停功能，但项目扫描涉及模块较多，目前还没能较好的实现暂停任务，后面会考虑添加。
