### ISSUE TITLE
ssh爆破时出现问题

### ISSUE THREAD

**Issue by InkNull** [TideSec/TscanPlus#89]
在ssh爆破，发现爆破数据多一点时（测试时大概有500多个枚举请求），账户密码爆不出来（多次尝试好像也不太行），换个类似的工具好像可以：
![image](https://github.com/user-attachments/assets/9c2ba67c-5c32-43b8-851b-73b51c02dd59)
![image](https://github.com/user-attachments/assets/a1f8287f-41d9-4556-a5f7-3377e46aa905)

![image](https://github.com/user-attachments/assets/3e360918-6fa7-454c-8f03-382a0323a5c9)

![image](https://github.com/user-attachments/assets/5a9b5225-f577-4742-b322-4219be5e72cc)
![image](https://github.com/user-attachments/assets/5e14f493-bc50-47cb-a029-b6bdcd5eca63)

**Comment by TideSec** [comment]
感谢师傅反馈，我先记录一下，后期会复现并修复。
