### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by liuhanyu200** [TideSec/TscanPlus#92]
![image](https://github.com/user-attachments/assets/952f9f18-34d8-4bc5-b343-5cfc7d193cc0)
阅读了很多遍，还是不能通过，这是bug吗

**Comment by TideSec** [comment]
你用的可能是windows，且分辨率比较小，所以看不到上面的标签，你可以调整下分辨率，或者下载v2.2最新版，有个全屏按钮，就可以了。
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/be4ed99f-a83a-4279-92ab-59a925e2fba5">
