### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by jobsgxx** [TideSec/TscanPlus#98]
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

![image](https://github.com/user-attachments/assets/0fff00be-8384-4e13-8800-c8bd98a3b400)

**Comment by TideSec** [comment]
建议师傅更换22.04或kali2023之后版本，或者根据这个https://github.com/TideSec/TscanPlus?tab=readme-ov-file#faq，安装lib库。
<img width="877" alt="image" src="https://github.com/user-attachments/assets/e6436599-a1e1-411c-9bdf-2f8a89e1a6cd">
